### PR TITLE
Fix createStore composition in dev mode

### LINKED ISSUE #10: Uncaught TypeError: store.getState is not a function
I just create a empty app with 'yo redux' 
Got error message from dev console.

### PR DESCRIPTION
**Pull request by pdf**
Disclaimer: I have programmed 0 hours of react and ES6, this is a naive fix based on the redux-devtools README, so that I can get started.

Fixes #10

### CODE REVIEW

File: generators/app/templates/js/store/configureStore.js [hunk 1]
```diff
@@ -6,13 +6,12 @@ let createStoreWithMiddleware;
 
 // Configure the dev tools when in DEV mode
 if (__DEV__) {
-  let {devTools, persistState} = require('redux-devtools');
+  const {devTools, persistState} = require('redux-devtools');
```
Comment (proshunsuke) [inline generators/app/templates/js/store/configureStore.js:9]: It would be better to fix [this](https://github.com/banderson/generator-redux/blob/master/generators/app/templates/js/utils/devTools.js#L5) too, I think.
from `let` to `const`

Comment (pdf) [inline generators/app/templates/js/store/configureStore.js:9]: There are a whole bunch of lint errors/warnings, I was going to submit them in a separate PR

Comment (proshunsuke) [inline generators/app/templates/js/store/configureStore.js:9]: OK! I understand. Thanks!

**Comment by banderson** [comment]
Thanks!
